package com.vehicle300.demo.dao;

import com.vehicle300.demo.example.MobileInfoExample;
import com.vehicle300.demo.model.MobileInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MobileInfoMapper {
    long countByExample(MobileInfoExample example);

    int deleteByExample(MobileInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(MobileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") MobileInfo record, @Param("selective") MobileInfo.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MobileInfo selectOneByExample(MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MobileInfo selectOneByExampleSelective(@Param("example") MobileInfoExample example, @Param("selective") MobileInfo.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MobileInfo> selectByExampleSelective(@Param("example") MobileInfoExample example, @Param("selective") MobileInfo.Column... selective);

    List<MobileInfo> selectByExample(MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MobileInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MobileInfo.Column... selective);

    MobileInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") MobileInfo record, @Param("example") MobileInfoExample example, @Param("selective") MobileInfo.Column... selective);

    int updateByExample(@Param("record") MobileInfo record, @Param("example") MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") MobileInfo record, @Param("selective") MobileInfo.Column... selective);

    int updateByPrimaryKey(MobileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<MobileInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<MobileInfo> list, @Param("selective") MobileInfo.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(MobileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") MobileInfo record, @Param("selective") MobileInfo.Column... selective);
}